openapi: 3.0.0
info:
  title: PPTX to JSON Conversion API
  description: |
    将 PowerPoint (PPTX) 文件转换为 PPTist 兼容的 JSON 格式的 REST API 服务。

    **核心功能**:
    - 上传 PPTX 文件并创建异步转换任务
    - 查询任务状态和进度
    - 下载转换结果（JSON 或 ZIP 包含媒体文件）
    - 批量转换支持

    **技术特性**:
    - 异步任务队列架构
    - 支持 100MB 文件
    - 可插拔队列存储（内存/Redis）
    - 版本化转换器（支持多版本 PPTist）
  version: 1.0.0
  contact:
    name: PPTist Backend Team
    email: backend@pptist.example.com
  license:
    name: MIT

servers:
  - url: http://localhost:3000/api/v1
    description: 本地开发环境
  - url: https://api.pptist.example.com/api/v1
    description: 生产环境

tags:
  - name: Conversion
    description: PPTX 文件转换操作
  - name: Tasks
    description: 任务查询和管理
  - name: Health
    description: 健康检查端点

paths:
  /convert:
    post:
      tags:
        - Conversion
      summary: 上传 PPTX 文件并创建转换任务
      description: |
        上传 PPTX 文件，创建异步转换任务，返回任务 ID。
        系统立即返回任务 ID，转换在后台异步执行。
      operationId: createConversionTask
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: PPTX 文件（最大 100MB）
                targetVersion:
                  type: string
                  description: 目标 PPTist 版本
                  enum: ["v1", "v2", "latest"]
                  default: "latest"
      responses:
        '201':
          description: 任务创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCreatedResponse'
        '400':
          description: 请求错误（文件格式错误、文件过大等）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: 文件过大（超过 100MB）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /convert/batch:
    post:
      tags:
        - Conversion
      summary: 批量上传 PPTX 文件并创建多个转换任务
      description: |
        一次上传多个 PPTX 文件，为每个文件创建独立的转换任务。
        返回所有任务的 ID，可使用这些 ID 查询各自的状态。
      operationId: createBatchConversionTasks
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - files
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
                  description: PPTX 文件数组（最多 10 个，每个最大 100MB）
                targetVersion:
                  type: string
                  description: 目标 PPTist 版本
                  enum: ["v1", "v2", "latest"]
                  default: "latest"
      responses:
        '201':
          description: 批量任务创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchTaskCreatedResponse'
        '400':
          description: 请求错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '413':
          description: 文件过大或文件数量过多
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tasks/{taskId}:
    get:
      tags:
        - Tasks
      summary: 查询任务状态和进度
      description: |
        通过任务 ID 查询任务的当前状态、进度和结果（如果已完成）。
      operationId: getTaskStatus
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: 任务 ID（UUID v4）
      responses:
        '200':
          description: 任务状态查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatusResponse'
        '404':
          description: 任务不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服务器错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tasks/batch:
    post:
      tags:
        - Tasks
      summary: 批量查询任务状态
      description: |
        一次查询多个任务的状态，返回汇总信息。
      operationId: getBatchTaskStatus
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - taskIds
              properties:
                taskIds:
                  type: array
                  items:
                    type: string
                    format: uuid
                  maxItems: 100
                  description: 任务 ID 数组（最多 100 个）
      responses:
        '200':
          description: 批量查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchTaskStatusResponse'
        '400':
          description: 请求错误（taskIds 数量超过限制等）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tasks/{taskId}/result:
    get:
      tags:
        - Tasks
      summary: 下载转换结果（JSON 文件）
      description: |
        下载转换后的 JSON 文件。如果任务未完成，返回 404。
      operationId: downloadTaskResult
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: 任务 ID
      responses:
        '200':
          description: 转换结果下载成功
          content:
            application/json:
              schema:
                type: object
                description: PPTist 格式的 JSON 数据
          headers:
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="pptist-abc123.json"
            X-API-Version:
              schema:
                type: string
                example: v1
        '404':
          description: 任务不存在或未完成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tasks/{taskId}/result/zip:
    get:
      tags:
        - Tasks
      summary: 下载转换结果（ZIP 包，包含 JSON 和媒体文件）
      description: |
        下载包含 JSON 结果和所有提取的媒体文件的 ZIP 压缩包。
        仅当任务已完成且存在提取的媒体文件时可用。
      operationId: downloadTaskResultZIP
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: 任务 ID
      responses:
        '200':
          description: ZIP 文件下载成功
          content:
            application/zip:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              schema:
                type: string
                example: attachment; filename="pptist-abc123.zip"
            X-API-Version:
              schema:
                type: string
                example: v1
        '404':
          description: 任务不存在、未完成或无可用的媒体文件
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /tasks/{taskId}/preview:
    get:
      tags:
        - Tasks
      summary: 获取转换结果预览（元数据）
      description: |
        返回转换结果的元数据信息（幻灯片数量、元素统计、警告列表），
        不包含完整的 JSON 数据。用于用户在下载前验证转换结果。
      operationId: getTaskPreview
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: 任务 ID
      responses:
        '200':
          description: 预览信息获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskPreviewResponse'
        '404':
          description: 任务不存在或未完成
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      tags:
        - Health
      summary: 健康检查端点
      description: |
        返回服务健康状态，用于容器编排（Kubernetes/Docker）的健康检查。
      operationId: healthCheck
      responses:
        '200':
          description: 服务健康
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
        '503':
          description: 服务不健康
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'

components:
  schemas:
    TaskCreatedResponse:
      type: object
      required:
        - taskId
        - status
        - createdAt
      properties:
        taskId:
          type: string
          format: uuid
          description: 任务 ID
        status:
          type: string
          enum: ["queued", "processing"]
          description: 任务初始状态
        createdAt:
          type: string
          format: date-time
          description: 任务创建时间

    BatchTaskCreatedResponse:
      type: object
      required:
        - taskIds
        - total
      properties:
        taskIds:
          type: array
          items:
            type: string
            format: uuid
          description: 所有创建的任务 ID 数组
        total:
          type: integer
          description: 创建的任务总数

    TaskStatusResponse:
      type: object
      required:
        - taskId
        - status
        - progress
        - createdAt
      properties:
        taskId:
          type: string
          format: uuid
        status:
          type: string
          enum: ["queued", "processing", "completed", "failed"]
        progress:
          type: integer
          minimum: 0
          maximum: 100
          description: 进度百分比（0-100）
        createdAt:
          type: string
          format: date-time
        startedAt:
          type: string
          format: date-time
          nullable: true
        completedAt:
          type: string
          format: date-time
          nullable: true
        result:
          $ref: '#/components/schemas/ConversionResult'
          nullable: true
        error:
          $ref: '#/components/schemas/ErrorDetail'
          nullable: true

    BatchTaskStatusResponse:
      type: object
      required:
        - tasks
        - summary
      properties:
        tasks:
          type: object
          description: 任务 ID 到任务状态的映射
          additionalProperties:
            $ref: '#/components/schemas/TaskStatusResponse'
        summary:
          type: object
          required:
            - total
            - queued
            - processing
            - completed
            - failed
          properties:
            total:
              type: integer
            queued:
              type: integer
            processing:
              type: integer
            completed:
              type: integer
            failed:
              type: integer

    TaskPreviewResponse:
      type: object
      required:
        - taskId
        - status
        - metadata
      properties:
        taskId:
          type: string
          format: uuid
        status:
          type: string
          enum: ["completed", "failed"]
        metadata:
          $ref: '#/components/schemas/ConversionMetadata'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/ConversionWarning'

    ConversionResult:
      type: object
      required:
        - slides
        - metadata
        - pptistVersion
      properties:
        slides:
          type: array
          description: PPTist 格式的幻灯片数组
          items:
            type: object
            description: PPTist Slide 对象（结构详见 PPTist types/slides.ts）
        metadata:
          $ref: '#/components/schemas/ConversionMetadata'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/ConversionWarning'
        pptistVersion:
          type: string
          description: 输出对应的 PPTist 版本

    ConversionMetadata:
      type: object
      required:
        - slideCount
        - elementStats
        - processingDuration
        - fileSize
        - targetVersion
      properties:
        slideCount:
          type: integer
          description: 幻灯片总数
        elementStats:
          type: object
          description: 各类型元素数量统计
          required:
            - text
            - image
            - shape
            - line
            - chart
            - table
            - video
            - audio
          properties:
            text:
              type: integer
            image:
              type: integer
            shape:
              type: integer
            line:
              type: integer
            chart:
              type: integer
            table:
              type: integer
            video:
              type: integer
            audio:
              type: integer
        processingDuration:
          type: integer
          description: 处理时长（毫秒）
        fileSize:
          type: integer
          description: 原始文件大小（bytes）
        targetVersion:
          type: string
          description: 目标 PPTist 版本
        extractedMedia:
          type: object
          description: 提取的媒体文件信息
          required:
            - images
            - videos
            - audios
          properties:
            images:
              type: array
              items:
                type: string
            videos:
              type: array
              items:
                type: string
            audios:
              type: array
              items:
                type: string

    ConversionWarning:
      type: object
      required:
        - type
        - message
      properties:
        type:
          type: string
          enum: ["UNSUPPORTED_ELEMENT", "DOWNGRADED", "MISSING_MEDIA"]
        elementId:
          type: string
          description: 受影响的元素 ID
        message:
          type: string
          description: 警告消息
        suggestion:
          type: string
          description: 建议操作

    ErrorDetail:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum: ["INVALID_FORMAT", "PARSE_ERROR", "FILE_TOO_LARGE", "ENCRYPTED", "CORRUPTED"]
        message:
          type: string
        details:
          type: object
          description: 错误详情（仅开发环境）

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: 错误消息
        requestId:
          type: string
          description: 请求 ID（用于追踪）
        timestamp:
          type: string
          format: date-time
          description: 错误时间戳

    HealthCheckResponse:
      type: object
      required:
        - status
        - version
      properties:
        status:
          type: string
          enum: ["healthy", "unhealthy"]
        version:
          type: string
          description: API 版本
        uptime:
          type: number
          description: 服务运行时长（秒）
        queue:
          type: object
          description: 任务队列状态
          properties:
            type:
              type: string
              enum: ["memory", "redis"]
            queued:
              type: integer
            processing:
              type: integer

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: |
        注意：当前版本为公开 API，无需认证。
        此 security scheme 为未来扩展预留。

security: []
